### ISSUE TITLE
Settlement Enclave: Signing and verification of QLDB updates

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#1747]
Implementation details still TBD, pending confirmation by @hspencer77 that we can achieve the desired properties via KMS keys alone:

KMS signing key desired properties: Only the enclave can sign, operators can verify, immutable - no one should be able to change who can sign, retain deletion permissions for root

Alternatively we would need a long term signing key.

**Comment by hspencer77** [comment]
### KMS Cryptographic Details

- https://docs.aws.amazon.com/kms/latest/cryptographic-details/intro.html

### Asymmetric Key Specs

- https://docs.aws.amazon.com/kms/latest/developerguide/asymmetric-key-specs.html#key-spec-ecc (figured this is what we would want to use)

### Symmetric Key Spec

- https://docs.aws.amazon.com/kms/latest/developerguide/asymmetric-key-specs.html#key-spec-symmetric-default

**Comment by hspencer77** [comment]
> retain deletion permissions for root

Should this be denying the root account but allowing someone from `security` to delete the key?

**Comment by hspencer77** [comment]
### Asymmetric Key Spec Options

With regards to signing/validating, I think the key spec will be either of the following:
- `ECC_NIST_P521 (secp521r1)`
- `ECC_SECG_P256K1`

### KMS Immutable Properties

We can make KMS keys immutable by doing the following:
- when performing KMS `CreateKey` API calls, pass [`BypassPolicyLockoutSafetyCheck`](https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html#API_CreateKey_RequestSyntax) flag set to `true`.  When this flag is set, the IAM entity can create the KMS key and attach a KMS key policy.  If the IAM entity tries to modify the KMS key policy, the following error gets returned (example):

```
Error: updating KMS Key (b4e071d6-c590-47e1-889f-da22d40b3d41): updating policy: AccessDeniedException: User: arn:aws:sts::021268868874:assumed-role/devops-admin-rw-role/1675902602864646000 is not authorized to perform: kms:PutKeyPolicy on resource: arn:aws:kms:us-west-2:021268868874:key/b4e071d6-c590-47e1-889f-da22d40b3d41 because no resource-based policy allows the kms:PutKeyPolicy action
```
- The KMS Key policy allows the IAM principal that creates the KMS key the following API calls:
      - `kms:CreateKey`
      - `kms:CreateAlias`
      - `kms:Describe*`
      - `kms:EnableKeyRotation`
      - `kms:EnableKey`
      -  `kms:ListAliases`
      - `kms:ListGrants`
      - `kms:ListKeyPolicies`
      - `kms:ListResourceTags`
      - `kms:ListRetireableGrants`
      - `kms:GetKeyPolicy`
      - `kms:GetKeyRotationStatus`
      - `kms:TagResource`
 - Have an IAM principal in the same AWS account that can `kms:Revoke*`, `kms:Disable*`, `kms:UntagResource`, `kms:Delete*`, `kms:ScheduleKeyDeletion`.  Currently this is the `security-admin-rw-role`, which can only be assumed by IAM entities in the `security-infosec` AWS account (_this is needed to delete old KMS keys to manage costs_). This has to be an IAM entity in the same AWS account associated to the KMS key because cross-account IAM entities are not allowed to perform `kms:Delete*`.

**Comment by hspencer77** [comment]
Another question I have as well:  should KMS keys be multi-region (disaster recovery)?
